### ISSUE TITLE
Deploy Gogs Demo App to Fly.io! 🚀 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gogs-demo#3]
The demo app in this repo _already_ shows displaying content from Gogs. 
But I want to show _updating_ content e.g ...
Once that is done, we should _immediately_ deploy it to Fly.io to showcase it!

**Comment by nelsonic** [comment]
```sh
1 desired, 1 placed, 0 healthy, 1 unhealthy
v2 failed - Failed due to unhealthy allocations - no stable job version to auto revert to
***v2 failed - Failed due to unhealthy allocations - no stable job version to auto revert to and deploying as v3

Troubleshooting guide at https://fly.io/docs/getting-started/troubleshooting/
Error abort
```

Re-reading: https://fly.io/docs/getting-started/troubleshooting

**Comment by nelsonic** [comment]
https://fly.io/apps/gogs-demo
![image](https://user-images.githubusercontent.com/194400/168172928-2092ed62-5e03-4a03-9038-7f98c47d9f69.png)

this is tedious ...

**Comment by nelsonic** [comment]
Log:
```sh
Recent Events
TIMESTAMP           	TYPE      	MESSAGE
2022-05-12T21:40:07Z	Received  	Task received by client
2022-05-12T21:40:07Z	Task Setup	Building Task Directory
2022-05-12T21:40:14Z	Started   	Task started by client

2022-05-12T21:40:08Z   [info]Starting instance
2022-05-12T21:40:09Z   [info]Configuring virtual machine
2022-05-12T21:40:09Z   [info]Pulling container image
2022-05-12T21:40:12Z   [info]Unpacking image
2022-05-12T21:40:13Z   [info]Preparing kernel init
2022-05-12T21:40:14Z   [info]Configuring firecracker
2022-05-12T21:40:14Z   [info]Starting virtual machine
2022-05-12T21:40:14Z   [info]Starting init (commit: 252b7bd)...
2022-05-12T21:40:14Z   [info]Preparing to run: `bin/app start` as nobody
2022-05-12T21:40:14Z   [info]2022/05/12 21:40:14 listening on [fdaa:0:5cce:a7b:a9a:d6:e7f5:2]:22 (DNS: [fdaa::3]:53)
2022-05-12T21:40:15Z   [info]Reaped child process with pid: 549, exit code: 0
2022-05-12T21:40:17Z   [info]Warning: the `dialyxir` application's start function was called, which likely means you
2022-05-12T21:40:17Z   [info]did not add the dependency with the `runtime: false` flag. This is not recommended because
2022-05-12T21:40:17Z   [info]it will mean that unnecessary applications are started, and unnecessary applications are most
2022-05-12T21:40:17Z   [info]likely being added to your PLT file, increasing build time.
2022-05-12T21:40:17Z   [info]Please add `runtime: false` in your `mix.exs` dependency section e.g.:
2022-05-12T21:40:17Z   [info]{:dialyxir, "~> 0.5", only: [:dev], runtime: false}
2022-05-12T21:40:17Z   [info]Reaped child process with pid: 570 and signal: SIGUSR1, core dumped? false
--> v8 failed - Failed due to unhealthy allocations - no stable job version to auto revert to and deploying as v9

--> Troubleshooting guide at https://fly.io/docs/getting-started/troubleshooting/
Error abort
```

**Comment by SimonLab** [comment]
Current error:
![image](https://user-images.githubusercontent.com/6057298/168244488-cff23a9e-ee8b-4a07-81b8-5607e42c86cd.png)

- [ ] Are all env variables defined on Fly? (We should maybe raised an error on gogs if they aren't.)

**Comment by nelsonic** [comment]
I've borrowed from our _successful_ deployment to Fly: https://github.com/dwyl/hits/pull/128/files

This time deploy worked:

```sh
n@MBP gogs-demo % flyctl deploy --verbose
==> Verifying app config
--> Verified app config
==> Building image
Remote builder fly-builder-shy-sunset-4953 ready
==> Creating build context
--> Creating build context done
==> Building image with Docker
--> docker host: 20.10.12 linux x86_64
[+] Building 13.5s (0/1)
[+] Building 63.5s (24/24) FINISHED
 => [internal] load remote build context                                                      0.0s
 => copy /context /                                                                           0.8s
 => [internal] load metadata for docker.io/library/alpine:3.13.3                              0.9s
 => [internal] load metadata for docker.io/hexpm/elixir:1.12.1-erlang-24.0.1-alpine-3.13.3    0.9s
 => [build  1/14] FROM docker.io/hexpm/elixir:1.12.1-erlang-24.0.1-alpine-3.13.3@sha256:4eef  0.0s
 => [app 1/5] FROM docker.io/library/alpine:3.13.3@sha256:826f70e0ac33e99a72cf20fb0571245a8f  0.0s
 => CACHED [build  2/14] RUN apk add --no-cache build-base npm                                0.0s
 => CACHED [build  3/14] WORKDIR /app                                                         0.0s
 => CACHED [build  4/14] RUN mix local.hex --force &&     mix local.rebar --force             0.0s
 => CACHED [build  5/14] COPY mix.exs mix.lock ./                                             0.0s
 => [build  6/14] COPY config config                                                          0.2s
 => [build  7/14] RUN mix deps.get --only prod &&     mix deps.compile                       54.2s
 => [build  8/14] COPY priv priv                                                              0.0s
 => [build  9/14] COPY assets assets                                                          0.0s
 => [build 10/14] RUN mix assets.deploy                                                       2.3s
 => [build 11/14] RUN mix phx.digest                                                          1.4s
 => [build 12/14] COPY lib lib                                                                0.0s
 => [build 13/14] COPY rel rel                                                                0.0s
 => [build 14/14] RUN mix do compile, release                                                 3.0s
 => CACHED [app 2/5] RUN apk add --no-cache libstdc++ openssl ncurses-libs                    0.0s
 => CACHED [app 3/5] WORKDIR /app                                                             0.0s
 => CACHED [app 4/5] RUN chown nobody:nobody /app                                             0.0s
 => [app 5/5] COPY --from=build --chown=nobody:nobody /app/_build/prod/rel/app ./             0.2s
 => exporting to image                                                                        0.2s
 => => exporting layers                                                                       0.2s
 => => writing image sha256:cd7784ee671f6ae4dfb1035bc5809360c43fae35c55c58578c103831965f6987  0.0s
 => => naming to registry.fly.io/gogs-demo:deployment-1652430611                              0.0s
--> Building image done
==> Pushing image to fly
The push refers to repository [registry.fly.io/gogs-demo]
2643d50a555d: Pushed
18c9d9e3d463: Layer already exists
6730b158cab8: Layer already exists
79ee22496eec: Layer already exists
0f7b3ff8b310: Layer already exists
deployment-1652430611: digest: sha256:622e88f7b825a004a303d1721c896aab1e7beaaaf0c24d22886e7662856def23 size: 1364
--> Pushing image done
image: registry.fly.io/gogs-demo:deployment-1652430611
image size: 23 MB
==> Creating release
--> release v10 created

--> You can detach the terminal anytime without stopping the deployment
==> Monitoring deployment

 1 desired, 1 placed, 1 healthy, 0 unhealthy [health checks: 1 total, 1 passing]
--> v10 deployed successfully
```

But the app throws the following error: https://gogs-demo.fly.dev/
![image](https://user-images.githubusercontent.com/194400/168244572-fb7d40ea-91d4-4345-9eb3-5fdd2f8474bc.png)

```sh
2022-05-13T08:32:06Z app[416650a5] lhr [info]Server: gogs-demo.fly.dev:80 (http)
2022-05-13T08:32:06Z app[416650a5] lhr [info]Request: GET /
2022-05-13T08:32:06Z app[416650a5] lhr [info]** (exit) an exception was raised:
2022-05-13T08:32:06Z app[416650a5] lhr [info]    ** (CaseClauseError) no case clause matching: []
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (hackney 1.18.1) /app/deps/hackney/src/hackney_url.erl:248: :hackney_url.parse_netloc/2
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (hackney 1.18.1) /app/deps/hackney/src/hackney.erl:351: :hackney.request/5
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (httpoison 1.8.1) lib/httpoison/base.ex:846: HTTPoison.Base.request/6
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (gogs 1.0.1) lib/gogs.ex:105: Gogs.remote_render_markdown_html/4
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:9: AppWeb.PageController.index/2
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.action/2
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.phoenix_controller_pipeline/2
2022-05-13T08:32:06Z app[416650a5] lhr [info]        (phoenix 1.6.8) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
2022-05-13T08:32:34Z runner[00d6e7f5] lhr [info]Shutting down virtual machine
2022-05-13T08:32:34Z app[00d6e7f5] lhr [info]Sending signal SIGTERM to main child process w/ PID 515
2022-05-13T08:32:34Z app[00d6e7f5] lhr [info]08:32:34.380 [info] SIGTERM received - shutting down
2022-05-13T08:32:37Z app[00d6e7f5] lhr [info]Main child exited normally with code: 0
2022-05-13T08:32:37Z app[00d6e7f5] lhr [info]Starting clean up.
2022-05-13T08:32:47Z app[416650a5] lhr [info]08:32:47.489 request_id=Fu6dBzAgTKuegE8AAADh [info] GET /
2022-05-13T08:32:47Z app[416650a5] lhr [info]08:32:47.489 request_id=Fu6dBzAgTKuegE8AAADh [info] Sent 500 in 619µs
2022-05-13T08:32:47Z app[416650a5] lhr [info]08:32:47.490 [error] #PID<0.1491.0> running AppWeb.Endpoint (connection #PID<0.1490.0>, stream id 1) terminated
2022-05-13T08:32:47Z app[416650a5] lhr [info]Server: gogs-demo.fly.dev:80 (http)
2022-05-13T08:32:47Z app[416650a5] lhr [info]Request: GET /
2022-05-13T08:32:47Z app[416650a5] lhr [info]** (exit) an exception was raised:
2022-05-13T08:32:47Z app[416650a5] lhr [info]    ** (CaseClauseError) no case clause matching: []
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (hackney 1.18.1) /app/deps/hackney/src/hackney_url.erl:248: :hackney_url.parse_netloc/2
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (hackney 1.18.1) /app/deps/hackney/src/hackney.erl:351: :hackney.request/5
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (httpoison 1.8.1) lib/httpoison/base.ex:846: HTTPoison.Base.request/6
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (gogs 1.0.1) lib/gogs.ex:105: Gogs.remote_render_markdown_html/4
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:9: AppWeb.PageController.index/2
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.action/2
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (app 0.1.0) lib/app_web/controllers/page_controller.ex:1: AppWeb.PageController.phoenix_controller_pipeline/2
2022-05-13T08:32:47Z app[416650a5] lhr [info]        (phoenix 1.6.8) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
```

**Comment by SimonLab** [comment]
`flyctl secrets list`
![image](https://user-images.githubusercontent.com/6057298/168245240-ddc766f7-b1a1-4953-b036-84490dd73056.png)
missing some environment variables

**Comment by nelsonic** [comment]
https://gogs-demo.fly.dev/init
![image](https://user-images.githubusercontent.com/194400/168248828-fcce6073-543a-4fec-b72e-8e777b243397.png)

**Comment by nelsonic** [comment]
Deployed: https://gogs-demo.fly.dev/ 🚀 
![image](https://user-images.githubusercontent.com/194400/168398126-05c147ef-7fcc-4867-8a05-c89669027674.png)

Working. ✅
